import './Character.js';
import './Bowerman.js';
import './Swordsman.js';
import './Magician.js';
import './Daemon.js';
import './Undead.js';
import './Zombie.js';
// import Bowerman from './Bowerman.js';
const Bowman = new Bowerman();
Bowman();
